// <auto-generated />
namespace Market.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ComputedFiyat2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ComputedFiyat2));
        
        string IMigrationMetadata.Id
        {
            get { return "201901100639077_ComputedFiyat2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
